/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 level16.gltf --transform
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/glb/level16-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (props.play) {
      actions["Key.008Action"].play();
    }
  }, [props.play]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="result_016">
          <mesh
            name="result-5_025"
            geometry={nodes["result-5_025"].geometry}
            material={materials.leaf_disease}
            morphTargetDictionary={nodes["result-5_025"].morphTargetDictionary}
            morphTargetInfluences={nodes["result-5_025"].morphTargetInfluences}
          />
          <mesh
            name="result-5_025_1"
            geometry={nodes["result-5_025_1"].geometry}
            material={materials.leaf_disease}
            morphTargetDictionary={
              nodes["result-5_025_1"].morphTargetDictionary
            }
            morphTargetInfluences={
              nodes["result-5_025_1"].morphTargetInfluences
            }
          />
          <mesh
            name="result-5_025_2"
            geometry={nodes["result-5_025_2"].geometry}
            material={materials.leaf_disease}
            morphTargetDictionary={
              nodes["result-5_025_2"].morphTargetDictionary
            }
            morphTargetInfluences={
              nodes["result-5_025_2"].morphTargetInfluences
            }
          />
          <mesh
            name="result-5_025_3"
            geometry={nodes["result-5_025_3"].geometry}
            material={materials.leaf_disease}
            morphTargetDictionary={
              nodes["result-5_025_3"].morphTargetDictionary
            }
            morphTargetInfluences={
              nodes["result-5_025_3"].morphTargetInfluences
            }
          />
          <mesh
            name="result-5_025_4"
            geometry={nodes["result-5_025_4"].geometry}
            material={materials.petals}
            morphTargetDictionary={
              nodes["result-5_025_4"].morphTargetDictionary
            }
            morphTargetInfluences={
              nodes["result-5_025_4"].morphTargetInfluences
            }
          />
          <mesh
            name="result-5_025_5"
            geometry={nodes["result-5_025_5"].geometry}
            material={materials.stamens}
            morphTargetDictionary={
              nodes["result-5_025_5"].morphTargetDictionary
            }
            morphTargetInfluences={
              nodes["result-5_025_5"].morphTargetInfluences
            }
          />
          <mesh
            name="result-5_025_6"
            geometry={nodes["result-5_025_6"].geometry}
            material={materials.stem}
            morphTargetDictionary={
              nodes["result-5_025_6"].morphTargetDictionary
            }
            morphTargetInfluences={
              nodes["result-5_025_6"].morphTargetInfluences
            }
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/glb/level16-transformed.glb");
