/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 level11.gltf --transform
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/glb/level11-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (props.play) {
      actions["Key.005Action"].play();
    }
  }, [props.play]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="result_011">
          <mesh
            name="result-5_007"
            geometry={nodes["result-5_007"].geometry}
            material={materials.leaf_disease}
            morphTargetDictionary={nodes["result-5_007"].morphTargetDictionary}
            morphTargetInfluences={nodes["result-5_007"].morphTargetInfluences}
          />
          <mesh
            name="result-5_007_1"
            geometry={nodes["result-5_007_1"].geometry}
            material={materials.leaf_disease}
            morphTargetDictionary={
              nodes["result-5_007_1"].morphTargetDictionary
            }
            morphTargetInfluences={
              nodes["result-5_007_1"].morphTargetInfluences
            }
          />
          <mesh
            name="result-5_007_2"
            geometry={nodes["result-5_007_2"].geometry}
            material={materials.leaf_disease}
            morphTargetDictionary={
              nodes["result-5_007_2"].morphTargetDictionary
            }
            morphTargetInfluences={
              nodes["result-5_007_2"].morphTargetInfluences
            }
          />
          <mesh
            name="result-5_007_3"
            geometry={nodes["result-5_007_3"].geometry}
            material={materials.leaf_disease}
            morphTargetDictionary={
              nodes["result-5_007_3"].morphTargetDictionary
            }
            morphTargetInfluences={
              nodes["result-5_007_3"].morphTargetInfluences
            }
          />
          <mesh
            name="result-5_007_4"
            geometry={nodes["result-5_007_4"].geometry}
            material={materials.petals}
            morphTargetDictionary={
              nodes["result-5_007_4"].morphTargetDictionary
            }
            morphTargetInfluences={
              nodes["result-5_007_4"].morphTargetInfluences
            }
          />
          <mesh
            name="result-5_007_5"
            geometry={nodes["result-5_007_5"].geometry}
            material={materials.stamens}
            morphTargetDictionary={
              nodes["result-5_007_5"].morphTargetDictionary
            }
            morphTargetInfluences={
              nodes["result-5_007_5"].morphTargetInfluences
            }
          />
          <mesh
            name="result-5_007_6"
            geometry={nodes["result-5_007_6"].geometry}
            material={materials.stem}
            morphTargetDictionary={
              nodes["result-5_007_6"].morphTargetDictionary
            }
            morphTargetInfluences={
              nodes["result-5_007_6"].morphTargetInfluences
            }
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/glb/level11-transformed.glb");
