/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 level30-colored.gltf --transform
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/glb/level30-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (props.play) {
      actions["Key.028Action"].play();
    }
  }, [props.play]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="result_030">
          <mesh
            name="result-5_013"
            geometry={nodes["result-5_013"].geometry}
            material={materials["stem.001"]}
            morphTargetDictionary={nodes["result-5_013"].morphTargetDictionary}
            morphTargetInfluences={nodes["result-5_013"].morphTargetInfluences}
          />
          <mesh
            name="result-5_013_1"
            geometry={nodes["result-5_013_1"].geometry}
            material={materials["fruit-ripe"]}
            morphTargetDictionary={
              nodes["result-5_013_1"].morphTargetDictionary
            }
            morphTargetInfluences={
              nodes["result-5_013_1"].morphTargetInfluences
            }
          />
          <mesh
            name="result-5_013_2"
            geometry={nodes["result-5_013_2"].geometry}
            material={materials["leaf_disease.001"]}
            morphTargetDictionary={
              nodes["result-5_013_2"].morphTargetDictionary
            }
            morphTargetInfluences={
              nodes["result-5_013_2"].morphTargetInfluences
            }
          />
          <mesh
            name="result-5_013_3"
            geometry={nodes["result-5_013_3"].geometry}
            material={materials["leaf_disease.001"]}
            morphTargetDictionary={
              nodes["result-5_013_3"].morphTargetDictionary
            }
            morphTargetInfluences={
              nodes["result-5_013_3"].morphTargetInfluences
            }
          />
          <mesh
            name="result-5_013_4"
            geometry={nodes["result-5_013_4"].geometry}
            material={materials["leaf_disease.001"]}
            morphTargetDictionary={
              nodes["result-5_013_4"].morphTargetDictionary
            }
            morphTargetInfluences={
              nodes["result-5_013_4"].morphTargetInfluences
            }
          />
          <mesh
            name="result-5_013_5"
            geometry={nodes["result-5_013_5"].geometry}
            material={materials["leaf_disease.001"]}
            morphTargetDictionary={
              nodes["result-5_013_5"].morphTargetDictionary
            }
            morphTargetInfluences={
              nodes["result-5_013_5"].morphTargetInfluences
            }
          />
          <mesh
            name="result-5_013_6"
            geometry={nodes["result-5_013_6"].geometry}
            material={materials["stem.001"]}
            morphTargetDictionary={
              nodes["result-5_013_6"].morphTargetDictionary
            }
            morphTargetInfluences={
              nodes["result-5_013_6"].morphTargetInfluences
            }
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/glb/level30-transformed.glb");
