/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 level19.gltf --transform
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/glb/level19-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (props.play) {
      actions["Key.010Action"].play();
    }
  }, [props.play]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="result_019">
          <mesh
            name="result-5_028"
            geometry={nodes["result-5_028"].geometry}
            material={materials.leaf_disease}
            morphTargetDictionary={nodes["result-5_028"].morphTargetDictionary}
            morphTargetInfluences={nodes["result-5_028"].morphTargetInfluences}
          />
          <mesh
            name="result-5_028_1"
            geometry={nodes["result-5_028_1"].geometry}
            material={materials.leaf_disease}
            morphTargetDictionary={
              nodes["result-5_028_1"].morphTargetDictionary
            }
            morphTargetInfluences={
              nodes["result-5_028_1"].morphTargetInfluences
            }
          />
          <mesh
            name="result-5_028_2"
            geometry={nodes["result-5_028_2"].geometry}
            material={materials.leaf_disease}
            morphTargetDictionary={
              nodes["result-5_028_2"].morphTargetDictionary
            }
            morphTargetInfluences={
              nodes["result-5_028_2"].morphTargetInfluences
            }
          />
          <mesh
            name="result-5_028_3"
            geometry={nodes["result-5_028_3"].geometry}
            material={materials.leaf_disease}
            morphTargetDictionary={
              nodes["result-5_028_3"].morphTargetDictionary
            }
            morphTargetInfluences={
              nodes["result-5_028_3"].morphTargetInfluences
            }
          />
          <mesh
            name="result-5_028_4"
            geometry={nodes["result-5_028_4"].geometry}
            material={materials.petals}
            morphTargetDictionary={
              nodes["result-5_028_4"].morphTargetDictionary
            }
            morphTargetInfluences={
              nodes["result-5_028_4"].morphTargetInfluences
            }
          />
          <mesh
            name="result-5_028_5"
            geometry={nodes["result-5_028_5"].geometry}
            material={materials.stamens}
            morphTargetDictionary={
              nodes["result-5_028_5"].morphTargetDictionary
            }
            morphTargetInfluences={
              nodes["result-5_028_5"].morphTargetInfluences
            }
          />
          <mesh
            name="result-5_028_6"
            geometry={nodes["result-5_028_6"].geometry}
            material={materials.stem}
            morphTargetDictionary={
              nodes["result-5_028_6"].morphTargetDictionary
            }
            morphTargetInfluences={
              nodes["result-5_028_6"].morphTargetInfluences
            }
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/glb/level19-transformed.glb");
